Repository PleasPlan/OMO-project, pull requests merged in 2023-09, with the labels that each got.

#112 [FE] 나만의코스 버튼들 margin-bottom 추가, 나만의 코스 좋아요 관심 숫자 추가
  OMO-project/src/App.jsx
  OMO-project/src/components/MyCourse/Button/ComeBackList/ComeBackList.module.css
  OMO-project/src/components/MyCourse/Button/Edit-Share/Edit-Share.module.css
  OMO-project/src/components/MyCourse/Button/Save/Save.module.css
  OMO-project/src/components/MyCourse/MyCourseDataBox/MyCourseDataBox.module.css
  OMO-project/src/const/data.js
  OMO-project/src/pages/MyCourse/MyCouresMyVersion/MyCourseMyVersion.jsx
  OMO-project/src/pages/MyCourse/MyCourseMyVersionEdit/MyCourseMyVersionEdit.jsx
  OMO-project/src/pages/MyCourse/MyCourseOthersVersion/MyCourseOthersVersion.jsx
  OMO-project/src/pages/MyCourse/MyCourseWrite/MyCourseWrite.jsx
Labels: 🎨markup

#115 [BE] 예외처리 코드 추가
  src/main/java/com/OmObe/OmO/advice/GlobalExceptionAdvice.java
  src/main/java/com/OmObe/OmO/response/ErrorResponse.java
Labels: ✨feat

#116 [BE] 회원 탈퇴 처리
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: 🐞fix

#117 [Fe] Route 추가
  OMO-project/package-lock.json
  OMO-project/package.json
  OMO-project/src/App.jsx
  OMO-project/src/components/Header/Header.jsx
Labels: ✨feat

#118 Fe: route 경로 설정
  OMO-project/src/App.jsx
  OMO-project/src/components/Header/Header.jsx
  OMO-project/src/components/Mypage/Mypage.jsx
  OMO-project/src/components/MypageListBox/MypageListBox.jsx
  OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx
Labels: ✨feat

#119 Fe 나만의 코스 Route 설정
  OMO-project/src/App.jsx
  OMO-project/src/components/MyCourse/Button/Edit-Share/Edit-Share.jsx
  OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.jsx
  OMO-project/src/pages/MyCourse/MyCouresMyVersion/MyCourseMyVersion.jsx
  OMO-project/src/pages/MyCourse/MyCourseMain/MyCourseMain.jsx
  OMO-project/src/pages/MyCourse/MyCourseOthersVersion/MyCourseOthersVersion.jsx
  OMO-project/src/pages/MyCourse/MyCourseWrite/MyCourseWrite.jsx
Labels: ✨feat

#121 [Fe] 커뮤니티 글쓰기 버튼, 글쓰기 취소, 등록 버튼 Route 설정,App.jsx Route 로 바꾸기
  OMO-project/src/App.jsx
  OMO-project/src/components/WritingButton/WritingButton.jsx
  OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.jsx
  OMO-project/src/pages/Community/WriteBoard/WriteBoard.jsx
Labels: ✨feat

#124 [Fe] 커뮤니티 리뷰 작성 폼 기능
  OMO-project/src/App.jsx
  OMO-project/src/components/CommunityCategory/CommunityCategory.jsx
  OMO-project/src/components/CommunityPost/CommunityPost.jsx
  OMO-project/src/components/CommunityPost/CommunityPost.module.css
Labels: ✨feat
