Repository PleasPlan/OMO-project, pull requests merged in 2023-08, with the labels that each got.

#46 [markup] Mypage 마크업
  OMO-project/src/App.jsx
  OMO-project/src/components/Mypage/Mypage.jsx
  OMO-project/src/components/Mypage/Mypage.module.css
  OMO-project/src/pages/my-page/my-info/My-info.jsx
  OMO-project/src/pages/my-page/my-info/My-info.module.css
Labels: 🎨markup

#49 [markup] data 만들어서 map으로 뿌리기
  OMO-project/src/App.jsx
  OMO-project/src/components/Filter/Filter.jsx
  OMO-project/src/components/Filter/Filter.module.css
  OMO-project/src/components/Mypage-Filter/Mypage-Filter.jsx
  OMO-project/src/components/Mypage-Filter/Mypage-Filter.module.css
  OMO-project/src/components/Mypage-Wrote-main/Mypage-wrote-main.jsx
  OMO-project/src/components/Mypage-Wrote-main/Mypage-wrote-main.module.css
  OMO-project/src/components/Mypage/Mypage.jsx
  OMO-project/src/components/Mypage/Mypage.module.css
  OMO-project/src/const/myPageWrote.js
  OMO-project/src/pages/list/List.jsx
  OMO-project/src/pages/my-page/my-info/My-info.jsx
  OMO-project/src/pages/my-page/my-info/My-info.module.css
  OMO-project/src/pages/my-page/my-wrote/My-wrote.jsx
  OMO-project/src/pages/my-page/my-wrote/My-wrote.module.css
Labels: 🎨markup

#51 [markup] List페이지 filter 마크업 수정
  OMO-project/src/App.jsx
  OMO-project/src/components/Filter/Filter.jsx
  OMO-project/src/components/Filter/Filter.module.css
Labels: 🎨markup

#54 [markup] 나만의 코스 메인 페이지 마크업 구현 및 마이페이지 마크업 구현
  OMO-project/src/App.jsx
  OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.jsx
  OMO-project/src/components/MyCourse/MyCourseList/MyCourseList.module.css
  OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx
  OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.module.css
  OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.jsx
  OMO-project/src/components/MypageProfileSetting/MembershipWithdrawal/MembershipWithdrawal.module.css
  OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx
  OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.module.css
  OMO-project/src/components/MypageProfileSetting/PasswordChange/PasswordChange.jsx
  OMO-project/src/components/MypageProfileSetting/PasswordChange/PasswordChange.module.css
  OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx
  OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.module.css
  OMO-project/src/const/myCourse.js
  OMO-project/src/pages/MyCourse/MyCourse.jsx
  OMO-project/src/pages/MyCourse/MyCourse.module.css
  OMO-project/src/pages/Mypage/MyWrote/MyWrote.jsx
  OMO-project/src/pages/Mypage/ProfileSetting/ProfileSetting.jsx
  OMO-project/src/pages/Mypage/ProfileSetting/ProfileSetting.module.css
  OMO-project/src/pages/signup/Signup.jsx
  OMO-project/src/pages/signup/Signup.module.css
Labels: 🎨markup

#57 [markup] 공지사항 마크업 구현
  OMO-project/src/App.jsx
  OMO-project/src/components/Filter/Filter.jsx
  OMO-project/src/components/Filter/Filter.module.css
  OMO-project/src/components/Notice/Notice.jsx
  OMO-project/src/components/Notice/Notice.module.css
  OMO-project/src/const/listPageFilter.js
  OMO-project/src/const/myCourseFilter.js
  OMO-project/src/const/notice.js
  OMO-project/src/pages/list/List.jsx
  OMO-project/src/pages/list/List.module.css
  OMO-project/src/pages/notice/Notice.jsx
  OMO-project/src/pages/notice/Notice.module.css
Labels: 🎨markup

#66 Fe
  OMO-project/src/App.jsx
  OMO-project/src/pages/MyCourse/MyCourseMain/MyCourse.module.css
  OMO-project/src/pages/MyCourse/MyCourseWrite/MyCourseWrite.module.css
  OMO-project/src/pages/Mypage/Interest/Interest.module.css
  OMO-project/src/pages/Mypage/MyInfo/MyInfo.module.css
  OMO-project/src/pages/Mypage/MyWrote/MyWrote.module.css
  OMO-project/src/pages/community/Write-board/WriteBoard.jsx
  OMO-project/src/pages/community/Write-board/WriteBoard.module.css
  OMO-project/src/pages/notice/Notice.module.css
Labels: 🎨markup

#69 [BE] 소셜 로그인 구현
  build.gradle
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/jwt/TokenService.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/KakaoController.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/NaverController.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
  src/main/java/com/OmObe/OmO/auth/oauth/dto/KakaoProfile.java
  src/main/java/com/OmObe/OmO/auth/oauth/dto/NaverProfile.java
  src/main/java/com/OmObe/OmO/auth/oauth/dto/OAuthToken.java
  src/main/java/com/OmObe/OmO/auth/oauth/service/KakaoOAuthService.java
  src/main/java/com/OmObe/OmO/auth/oauth/service/NaverOAuthService.java
  src/main/java/com/OmObe/OmO/auth/oauth/service/OAuth2MemberService.java
  src/main/java/com/OmObe/OmO/member/dto/MemberDto.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/mapper/MemberMapper.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: ✨feat

#71 [BE] 로그인 사용자 인증 구현
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: 🐞fix, ✨feat

#80 [Fe] 커뮤니티 문의 게시판 자주하는 질문, QnA 마크업
  OMO-project/src/App.jsx
  OMO-project/src/components/CommunityInquiryBox/CommunityInquiryBox.jsx
  OMO-project/src/components/CommunityInquiryBox/CommunityInquiryBox.module.css
  OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.jsx
  OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.module.css
  OMO-project/src/components/Filter/Filter.module.css
  OMO-project/src/const/communityInquiryFrequent.js
  OMO-project/src/const/communityInquiryFrequentFilter.js
  OMO-project/src/const/communityQnAPost.js
  OMO-project/src/const/communityWorryPost.js
  OMO-project/src/const/themeCafe.js
  OMO-project/src/pages/Community/InquiryBoard/InquiryBoard.jsx
  OMO-project/src/pages/Community/InquiryBoard/InquiryBoard.module.css
  OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx
  OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.module.css
Labels: 🎨markup

#81 [markup] 커뮤니티 카테고리 재설정
  OMO-project/src/App.jsx
  OMO-project/src/components/CommunityCategory/CommunityCategory.jsx
  OMO-project/src/components/CommunityCategory/CommunityCategory.module.css
  OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.jsx
  OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.module.css
Labels: 🎨markup

#82 [BE] 로그아웃 구현
  build.gradle
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtLogoutFilter.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtVerificationFilter.java
  src/main/java/com/OmObe/OmO/redis/RedisConfig.java
  src/main/java/com/OmObe/OmO/redis/RedisService.java
Labels: ✨feat

#106 [BE] 게시글 관련 모든 코드 추기
  application.yml
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
  src/main/java/com/OmObe/OmO/Board/dto/BoardDto.java
  src/main/java/com/OmObe/OmO/Board/entity/Board.java
  src/main/java/com/OmObe/OmO/Board/mapper/BoardMapper.java
  src/main/java/com/OmObe/OmO/Board/repository/BoardRepository.java
  src/main/java/com/OmObe/OmO/Board/response/MultiResponseDto.java
  src/main/java/com/OmObe/OmO/Board/response/PageInfo.java
  src/main/java/com/OmObe/OmO/Board/service/BoardService.java
  src/main/java/com/OmObe/OmO/Comment/controller/CommentController.java
  src/main/java/com/OmObe/OmO/Comment/dto/CommentDto.java
  src/main/java/com/OmObe/OmO/Comment/entity/Comment.java
  src/main/java/com/OmObe/OmO/Comment/mapper/CommentMapper.java
  src/main/java/com/OmObe/OmO/Comment/repository/CommentRepository.java
  src/main/java/com/OmObe/OmO/Comment/service/CommentService.java
  src/main/java/com/OmObe/OmO/Liked/entity/Liked.java
  src/main/java/com/OmObe/OmO/Liked/repository/LikedRepository.java
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
Labels: ✨feat, ⚙setting

#107 [BE] 회원 관련 기능 수정
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/oauth/service/OAuth2MemberService.java
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/dto/MemberDto.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/mapper/MemberMapper.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: 🐞fix, ✨feat
