Repository PleasPlan/OMO-project, pull requests merged in 2023-07, with the labels that each got.

#4 프리티어 파일 추가
  OMO-project/.eslintrc.cjs
  OMO-project/.gitignore
  OMO-project/.prettierrc
  OMO-project/index.html
  OMO-project/package-lock.json
  OMO-project/package.json
  OMO-project/public/vite.svg
  OMO-project/src/App.css
  OMO-project/src/App.jsx
  OMO-project/src/assets/react.svg
  OMO-project/src/index.css
  OMO-project/src/main.jsx
  OMO-project/vite.config.js
Labels: ⚙setting

#13 [BE] 회원 기능 구현
  build.gradle
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/dto/MemberDto.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/mapper/MemberMapper.java
  src/main/java/com/OmObe/OmO/member/repository/MemberRepository.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
  src/test/java/com/OmObe/OmO/member/controller/MemberControllerTest.java
Labels: ✨feat

#14 [BE] 예외처리 코드 추가
  src/main/java/com/OmObe/OmO/exception/BusinessLogicException.java
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: ✨feat, 🧷chore

#15 [markup] 헤더 마크업 조정 및 메인 페이지 검색창 마크업
  OMO-project/index.html
  OMO-project/src/App.jsx
  OMO-project/src/App.module.css
  OMO-project/src/components/Header/Header.jsx
  OMO-project/src/components/Header/Header.module.css
  OMO-project/src/components/Search/Search.jsx
  OMO-project/src/components/Search/Search.module.css
  OMO-project/src/css/index.css
  OMO-project/src/css/normalize.css
  OMO-project/src/main.jsx
  OMO-project/src/pages/main/Main.jsx
  OMO-project/src/pages/main/Main.module.css
Labels: 🎨markup

#18 [markup] 메인페이지 검색창 마크업 최종
  OMO-project/src/components/Search/Search.jsx
  OMO-project/src/components/Search/Search.module.css
Labels: 🎨markup

#26 [BE] 스프링 시큐리티 적용
  build.gradle
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/userdetails/MemberDetailsService.java
  src/main/java/com/OmObe/OmO/auth/utils/MemberAuthorityUtils.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: ✨feat

#28 [BE] jwt 적용
  build.gradle
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtVerificationFilter.java
  src/main/java/com/OmObe/OmO/auth/handler/MemberAccessDeniedHandler.java
  src/main/java/com/OmObe/OmO/auth/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/OmObe/OmO/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/OmObe/OmO/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/jwt/JwtTokenizer.java
  src/main/java/com/OmObe/OmO/auth/utils/ErrorResponder.java
  src/main/java/com/OmObe/OmO/member/dto/MemberLoginDto.java
  src/main/java/com/OmObe/OmO/response/ErrorResponse.java
  src/test/java/com/OmObe/OmO/auth/jwt/JwtTokenizerTest.java
Labels: ✨feat

#30 [style] hover 시 그림자 추가
  OMO-project/src/components/CategoryBox/CategoryBox.jsx
  OMO-project/src/components/CategoryBox/CategoryBox.module.css
  OMO-project/src/components/Search/Search.module.css
Labels: 🔨style

#35 [BE] 비밀번호 확인 기능 추가
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/dto/MemberDto.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
  src/test/java/com/OmObe/OmO/member/controller/MemberControllerTest.java
  src/test/java/com/OmObe/OmO/member/service/MemberServiceTest.java
Labels: ✨feat

#37 [markup] Filter 컴포넌트, ListSearch 컴포넌트 UI 구현 및 List페이지 마크업 진행 중
  OMO-project/src/App.jsx
  OMO-project/src/components/Fliter/Filter.jsx
  OMO-project/src/components/Fliter/Filter.module.css
  OMO-project/src/components/ListSearch/ListSearch.jsx
  OMO-project/src/components/ListSearch/ListSearch.module.css
  OMO-project/src/components/Search/Search.jsx
  OMO-project/src/components/Search/Search.module.css
  OMO-project/src/pages/list/List.jsx
  OMO-project/src/pages/list/List.module.css
  OMO-project/src/pages/main/Main.jsx
  OMO-project/src/pages/sub/eating/Eating.jsx
  OMO-project/src/pages/sub/playing/Playing.jsx
  OMO-project/src/pages/sub/theme-cafe/ThemeCafe.jsx
  OMO-project/src/pages/sub/watching/Watching.jsx
Labels: 🎨markup

#38 [marklup] ListSearch maxLength 설정
  OMO-project/src/components/Fliter/Filter.module.css
  OMO-project/src/components/ListSearch/ListSearch.jsx
  OMO-project/src/components/ListSearch/ListSearch.module.css
Labels: 🎨markup
