Repository PleasPlan/OMO-project, pull requests merged in 2024-01, with the labels that each got.

#165 [feat] 커뮤니티 검색어 기능 추가
  OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx
  OMO-project/src/pages/Community/InquiryBoardFrequent/InquiryBoardFrequent.jsx
  OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx
  OMO-project/src/pages/Community/MyCourseBoard/MyCourseBoard.jsx
  OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx
Labels: ✨feat

#167 [BE] 회원 인증 기능 수정
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtVerificationFilter.java
  src/main/java/com/OmObe/OmO/auth/userdetails/MemberDetailsService.java
  src/main/java/com/OmObe/OmO/auth/utils/MemberAuthorityUtils.java
  src/main/java/com/OmObe/OmO/member/controller/MemberController.java
  src/main/java/com/OmObe/OmO/member/dto/MemberLoginDto.java
  src/main/java/com/OmObe/OmO/member/repository/MemberRepository.java
Labels: 🐞fix, ✨feat

#169 [BE] 사용자 검증 로직 수정, 게시판 & 리뷰 토큰 검증 로직 추가
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
  src/main/java/com/OmObe/OmO/Board/dto/BoardDto.java
  src/main/java/com/OmObe/OmO/Board/mapper/BoardMapper.java
  src/main/java/com/OmObe/OmO/Board/service/BoardService.java
  src/main/java/com/OmObe/OmO/Review/service/ReviewService.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: 🐞fix, ✨feat

#171 [BE] 공지사항 기능 구현
  build.gradle
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
  src/main/java/com/OmObe/OmO/notice/controller/NoticeController.java
  src/main/java/com/OmObe/OmO/notice/dto/NoticeDto.java
  src/main/java/com/OmObe/OmO/notice/entity/Notice.java
  src/main/java/com/OmObe/OmO/notice/mapper/NoticeMapper.java
  src/main/java/com/OmObe/OmO/notice/repository/NoticeRepository.java
  src/main/java/com/OmObe/OmO/notice/service/NoticeService.java
Labels: ✨feat

#174 [feat] content 안에 데이터 넣음
  OMO-project/src/components/MyCourse/MyCourseAfter/MyCourseAfter.jsx
  OMO-project/src/components/MyCourse/MyCourseFindBox/MyCourseFindBox.jsx
  OMO-project/src/components/MyCourse/MyCourseFindInterestModal/MyCourseFindInterestModal.jsx
  OMO-project/src/components/MyCourse/MyCourseItemListBox/MyCourseItemListBox.jsx
  OMO-project/src/components/MyCourse/MyCoursePlusBox/MyCoursePlusBox.jsx
  OMO-project/src/components/MyCourseEditor/MyCourseEditor.jsx
Labels: ✨feat

#179 [BE] 신고하기 기능 구현
  src/main/java/com/OmObe/OmO/Board/entity/Board.java
  src/main/java/com/OmObe/OmO/Board/repository/BoardRepository.java
  src/main/java/com/OmObe/OmO/Board/service/BoardService.java
  src/main/java/com/OmObe/OmO/Comment/controller/CommentController.java
  src/main/java/com/OmObe/OmO/Comment/entity/Comment.java
  src/main/java/com/OmObe/OmO/Comment/repository/CommentRepository.java
  src/main/java/com/OmObe/OmO/Comment/service/CommentService.java
  src/main/java/com/OmObe/OmO/Review/entity/Review.java
  src/main/java/com/OmObe/OmO/Review/mapper/ReviewMapper.java
  src/main/java/com/OmObe/OmO/Review/repository/ReviewRepository.java
  src/main/java/com/OmObe/OmO/advice/GlobalExceptionAdvice.java
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/exception/ExceptionCode.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/report/boardreport/controller/BoardReportController.java
  src/main/java/com/OmObe/OmO/report/boardreport/dto/BoardReportDto.java
  src/main/java/com/OmObe/OmO/report/boardreport/entity/BoardReport.java
  src/main/java/com/OmObe/OmO/report/boardreport/mapper/BoardReportMapper.java
  src/main/java/com/OmObe/OmO/report/boardreport/repository/BoardReportRepository.java
  src/main/java/com/OmObe/OmO/report/boardreport/service/BoardReportService.java
  src/main/java/com/OmObe/OmO/report/commentreport/controller/CommentReportController.java
  src/main/java/com/OmObe/OmO/report/commentreport/dto/CommentReportDto.java
  src/main/java/com/OmObe/OmO/report/commentreport/entity/CommentReport.java
  src/main/java/com/OmObe/OmO/report/commentreport/mapper/CommentReportMapper.java
  src/main/java/com/OmObe/OmO/report/commentreport/repository/CommentReportRepository.java
  src/main/java/com/OmObe/OmO/report/commentreport/service/CommentReportService.java
  src/main/java/com/OmObe/OmO/response/MultiPageResponseDto.java
Labels: ✨feat

#183 [BE] 토큰을 통해 서비스 접근 시 토큰 검증 로직 추가
  src/main/java/com/OmObe/OmO/Board/controller/BoardController.java
  src/main/java/com/OmObe/OmO/Board/dto/BoardDto.java
  src/main/java/com/OmObe/OmO/Board/service/BoardService.java
  src/main/java/com/OmObe/OmO/Comment/controller/CommentController.java
  src/main/java/com/OmObe/OmO/Comment/service/CommentService.java
  src/main/java/com/OmObe/OmO/Review/controller/ReviewController.java
  src/main/java/com/OmObe/OmO/Review/service/ReviewService.java
  src/main/java/com/OmObe/OmO/notice/controller/NoticeController.java
  src/main/java/com/OmObe/OmO/notice/service/NoticeService.java
  src/main/java/com/OmObe/OmO/report/boardreport/controller/BoardReportController.java
  src/main/java/com/OmObe/OmO/report/boardreport/service/BoardReportService.java
  src/main/java/com/OmObe/OmO/report/commentreport/controller/CommentReportController.java
  src/main/java/com/OmObe/OmO/report/commentreport/service/CommentReportService.java
Labels: 🐞fix, 🧷chore
