Repository PleasPlan/OMO-project, pull requests merged in 2024-02, with the labels that each got.

#190 [FE] 오류 수정
  OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.jsx
  OMO-project/src/components/SubCategoryBox/SubCategoryBox.jsx
  OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx
  OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx
  OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx
  OMO-project/src/pages/signup/Signup.jsx
Labels: 🐞fix

#191 [fix] 회원가입 페이지 import 대소문자 바꾸기
  OMO-project/src/App.jsx
Labels: 🐞fix

#192 [FE] 대소문자 오류 전체 수정
  OMO-project/src/App.jsx
  OMO-project/src/components/CommunityQnAPostList/CommunityQnAPostList.jsx
  OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.jsx
  OMO-project/src/components/MyCourse/MyCourseDataBox/MyCourseDataBox.jsx
  OMO-project/src/components/MyCourseDetailBox/MyCourseDetailBox.jsx
  OMO-project/src/pages/sub/ThemeCafe/ThemeCafe.jsx
  OMO-project/src/pages/sub/eating/Eating.jsx
  OMO-project/src/pages/sub/playing/Playing.jsx
  OMO-project/src/pages/sub/watching/Watching.jsx
Labels: 🐞fix

#196 [BE] 리프레시 토큰을 이용한 액세스 토큰 재발급 기능 구현
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/KakaoController.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/NaverController.java
  src/main/java/com/OmObe/OmO/auth/refreshtoken/RefreshTokenController.java
  src/main/java/com/OmObe/OmO/auth/refreshtoken/RefreshTokenService.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
  src/main/java/com/OmObe/OmO/redis/RedisService.java
Labels: 🐞fix, ✨feat

#198 [BE] 회원 정보 수정 기능 구현
  src/main/java/com/OmObe/OmO/MyPage/controller/MyPageController.java
  src/main/java/com/OmObe/OmO/MyPage/service/MyPageService.java
  src/main/java/com/OmObe/OmO/auth/userdetails/MemberDetailsService.java
  src/main/java/com/OmObe/OmO/member/dto/MemberDto.java
  src/main/java/com/OmObe/OmO/member/entity/Member.java
  src/main/java/com/OmObe/OmO/member/mapper/MemberMapper.java
  src/main/java/com/OmObe/OmO/member/service/MemberService.java
Labels: ✨feat

#200 Develop
  OMO-project/src/App.jsx
  OMO-project/src/components/CommunityQnAPostList/CommunityQnAPostList.jsx
  OMO-project/src/components/CommunityQnaBox/CommunityQnaBox.jsx
  OMO-project/src/components/ListBox/ListBox.jsx
  OMO-project/src/components/MyCourse/MyCourseDataBox/MyCourseDataBox.jsx
  OMO-project/src/components/MyCourseDetailBox/MyCourseDetailBox.jsx
  OMO-project/src/components/SubCategoryBox/SubCategoryBox.jsx
  OMO-project/src/pages/Community/FreeBoard/FreeBoard.jsx
  OMO-project/src/pages/Community/InquiryBoardQnA/InquiryBoardQnA.jsx
  OMO-project/src/pages/Community/WorryBoard/WorryBoard.jsx
  OMO-project/src/pages/Mypage/Recent/Recent.jsx
  OMO-project/src/pages/list/List.jsx
  OMO-project/src/pages/signup/Signup.jsx
  OMO-project/src/pages/sub/ThemeCafe/ThemeCafe.jsx
  OMO-project/src/pages/sub/eating/Eating.jsx
  OMO-project/src/pages/sub/playing/Playing.jsx
  OMO-project/src/pages/sub/watching/Watching.jsx
Labels: ✨feat

#201 [BE] 액세스 토큰 재발급 요청 오류 수정
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/OmObe/OmO/auth/filter/JwtLogoutFilter.java
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/jwt/TokenService.java
  src/main/java/com/OmObe/OmO/redis/RedisService.java
Labels: 🐞fix
