Repository PleasPlan/OMO-project, pull requests merged in 2024-05, with the labels that each got.

#231 Develop
  OMO-project/src/pages/LoginLoading/LoginLoading.jsx
  OMO-project/src/pages/login/Login.jsx
  OMO-project/src/pages/main/Main.jsx
Labels: ✨feat

#232 [feat] 로그인로딩 코드 수정
  OMO-project/src/pages/LoginLoading/LoginLoading.jsx
Labels: ✨feat

#235 [feat] 로그인 통신
  OMO-project/src/App.jsx
  OMO-project/src/pages/LoginLoading/LoginLoading.jsx
  OMO-project/src/pages/login/Login.jsx
Labels: ✨feat

#236 [markup] 회원가입 UI 변경
  OMO-project/src/pages/signup/Signup.jsx
  OMO-project/src/pages/signup/Signup.module.css
Labels: 🎨markup

#237 [BE] : Oauth 로그인 컨트롤러 추가
  src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
Labels: ✨feat

#239 [BE] oauth 로그인 후 토큰 처리 수정
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
Labels: 🐞fix

#238 [BE] oauth 로그인 후 토큰 처리 수정
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/OmObe/OmO/auth/oauth/controller/OAuthController.java
Labels: 🐞fix

#240 [BE] oauth 로그인 시 쿼리 파라미터로 최초 로그인 여부 전달
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: ✨feat

#241 [BE] oauth 로그인 후 쿼리 파라미터 전달 코드 수정
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🐞fix

#243 [BE] oauth 로그인 후 리다이렉트 경로 수정
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🐞fix

#244 [feat] 마이페이지 navigate 설정
  OMO-project/src/components/MypageProfileSetting/MbtiChange/MbtiChange.jsx
  OMO-project/src/components/MypageProfileSetting/NicknameChange/NicknameChange.jsx
  OMO-project/src/components/MypageProfileSetting/ProfileChange/ProfileChange.jsx
Labels: ✨feat

#245 [BE] CorsConfiguration 수정
  src/main/java/com/OmObe/OmO/auth/config/SecurityConfiguration.java
  src/main/java/com/OmObe/OmO/auth/config/WebConfig.java
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🐞fix

#247 [BE] oauth 로그인 후 리다이렉트 경로 수정(임시)
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🐞fix

#250 [BE] oauth 로그인 후 쿼리파라미터에 memberId 추가
  src/main/java/com/OmObe/OmO/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🐞fix

#252 [feat] 공지사항 통신
  OMO-project/src/pages/notice/Notice.jsx
  OMO-project/src/pages/notice/Notice.module.css
Labels: ✨feat

#253 [feat] 리스트페이지 썸네일 통신 중
  OMO-project/src/App.jsx
  OMO-project/src/assets/detail/EatingDefaultIcon.png
  OMO-project/src/assets/detail/defaultDetailIcon.png
  OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx
  OMO-project/src/components/ListBox/ListBox.jsx
  OMO-project/src/pages/Detail/DetailMenu/DetailMenu.jsx
  OMO-project/src/pages/list/List.jsx
Labels: ✨feat

#254 [feat] 리스트페이지 썸네일 수정
  OMO-project/src/App.jsx
  OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx
Labels: ✨feat

#257 [feat] 리뷰 프로토타입
  OMO-project/src/components/DetailItems/DetailItemsMenu/DetailItemsMenu.jsx
  OMO-project/src/components/DetailItems/Review/Review.jsx
Labels: ✨feat
